import 'dotenv/config';
import puppeteer from 'puppeteer';
import { readFileSync, mkdirSync } from 'node:fs';
import { uploadMedia } from './upload.js';

// ─── Load content generated by generate-content.js ───────────────────────
const content = JSON.parse(readFileSync('./output/slide-content.json', 'utf-8'));
const FOLDER_SLUG = content.folderSlug || 'tech-ai-news';

// ─── Brand colors ─────────────────────────────────────────────────────────
const BLUE = '#0A66C2';
const NAVY = '#0D1B2A';
const GREY = '#4A5568';
const WHITE = '#FFFFFF';
const BG = '#F7F9FC';

// ─── Generate HTML for each slide ────────────────────────────────────────
function getSlideHTML(slide, index) {
  const isHook = index === 0;
  const isCTA = index === 5;
  const slideNumber = index > 0 && !isCTA ? `0${index} / 05` : '';

  // Build center content based on slide content text
  const contentLines = slide.content.split(',').map(s => s.trim()).filter(Boolean);

  const centerContent = isCTA ? `
    <div class="cta-card">
      <div class="cta-title">What's coming next:</div>
      ${contentLines.slice(0, 4).map(line => {
        const parts = line.split(':');
        const title = parts[0]?.trim() || line;
        const desc = parts[1]?.trim() || '';
        return `<div class="bullet-row">
          <div class="bullet-dot"></div>
          <div><span class="bullet-title">${title}</span>${desc ? ` — <span class="bullet-desc">${desc}</span>` : ''}</div>
        </div>`;
      }).join('')}
    </div>
    <div class="cta-follow">Follow for weekly updates on AI and tech that actually matter.</div>
    <div class="cta-button">Follow for more →</div>
  ` : isHook ? `
    <div class="hook-grid">
      ${contentLines.slice(0, 6).map((item, i) => {
        const icons = ['🚀', '🧠', '💻', '🎨', '🌐', '⚡'];
        return `<div class="hook-card">
          <div class="hook-icon">${icons[i] || '✦'}</div>
          <div class="hook-label">${item}</div>
        </div>`;
      }).join('')}
    </div>
  ` : `
    <div class="content-cards">
      ${contentLines.slice(0, 4).map(line => {
        const parts = line.split(':');
        const title = parts[0]?.trim() || line;
        const desc = parts.slice(1).join(':')?.trim() || '';
        return `<div class="content-card">
          <div class="card-accent"></div>
          <div class="card-body">
            <div class="card-title">${title}</div>
            ${desc ? `<div class="card-desc">${desc}</div>` : ''}
          </div>
        </div>`;
      }).join('')}
    </div>
    <div class="visual-box">
      <div class="visual-icon">${getVisualEmoji(slide.visualDescription)}</div>
      <div class="visual-text">${slide.visualDescription?.substring(0, 80) || ''}</div>
    </div>
  `;

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    width: 1080px; height: 1080px;
    background: ${isHook ? WHITE : BG};
    font-family: 'Segoe UI', Arial, sans-serif;
    overflow: hidden;
    display: flex;
    flex-direction: column;
  }
  .slide {
    width: 1080px; height: 1080px;
    padding: 64px;
    display: flex;
    flex-direction: column;
    position: relative;
  }

  /* ── Top bar ── */
  .slide-number {
    font-size: 22px;
    color: ${BLUE};
    font-weight: 600;
    background: #E8F0FB;
    padding: 6px 16px;
    border-radius: 20px;
    display: inline-block;
    margin-bottom: 28px;
    width: fit-content;
  }
  .tag-pill {
    font-size: 22px;
    color: ${WHITE};
    font-weight: 700;
    background: ${BLUE};
    padding: 8px 20px;
    border-radius: 20px;
    display: inline-block;
    margin-bottom: 20px;
    width: fit-content;
    letter-spacing: 1px;
    text-transform: uppercase;
  }

  /* ── Headlines ── */
  .headline {
    font-size: 72px;
    font-weight: 900;
    color: ${NAVY};
    line-height: 1.1;
    text-transform: uppercase;
    margin-bottom: 8px;
  }
  .subheadline {
    font-size: 64px;
    font-weight: 900;
    color: ${WHITE};
    background: ${BLUE};
    padding: 4px 20px;
    display: inline-block;
    text-transform: uppercase;
    margin-bottom: 24px;
    line-height: 1.2;
  }
  .divider {
    width: 100%;
    height: 2px;
    background: ${BLUE};
    margin-bottom: 32px;
    opacity: 0.3;
  }

  /* ── Hook grid ── */
  .hook-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 20px;
    flex: 1;
  }
  .hook-card {
    background: ${WHITE};
    border: 2px solid ${BLUE}33;
    border-radius: 16px;
    padding: 24px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    border-left: 6px solid ${BLUE};
  }
  .hook-icon { font-size: 40px; margin-bottom: 12px; }
  .hook-label { font-size: 22px; font-weight: 700; color: ${NAVY}; text-align: center; }

  /* ── Content cards ── */
  .content-cards { display: flex; flex-direction: column; gap: 16px; flex: 1; }
  .content-card {
    background: ${WHITE};
    border: 1.5px solid ${BLUE}22;
    border-radius: 12px;
    display: flex;
    overflow: hidden;
  }
  .card-accent { width: 6px; background: ${BLUE}; flex-shrink: 0; }
  .card-body { padding: 16px 20px; }
  .card-title { font-size: 26px; font-weight: 700; color: ${NAVY}; margin-bottom: 4px; }
  .card-desc { font-size: 22px; color: ${GREY}; }

  /* ── Visual box ── */
  .visual-box {
    background: ${WHITE};
    border: 1.5px solid ${BLUE}22;
    border-radius: 12px;
    padding: 20px 24px;
    margin-top: 16px;
    display: flex;
    align-items: center;
    gap: 16px;
  }
  .visual-icon { font-size: 48px; }
  .visual-text { font-size: 22px; color: ${GREY}; flex: 1; }

  /* ── CTA ── */
  .cta-card {
    background: ${WHITE};
    border: 2px solid ${BLUE}33;
    border-radius: 16px;
    padding: 32px;
    flex: 1;
    border-top: 6px solid ${BLUE};
  }
  .cta-title { font-size: 28px; font-weight: 700; color: ${NAVY}; margin-bottom: 20px; }
  .bullet-row {
    display: flex;
    align-items: flex-start;
    gap: 12px;
    margin-bottom: 16px;
  }
  .bullet-dot {
    width: 12px; height: 12px;
    background: ${BLUE};
    border-radius: 50%;
    margin-top: 6px;
    flex-shrink: 0;
  }
  .bullet-title { font-size: 24px; font-weight: 700; color: ${NAVY}; }
  .bullet-desc { font-size: 22px; color: ${GREY}; }
  .cta-follow {
    font-size: 22px;
    color: ${GREY};
    text-align: center;
    margin-top: 20px;
    margin-bottom: 16px;
  }
  .cta-button {
    background: ${BLUE};
    color: ${WHITE};
    font-size: 24px;
    font-weight: 700;
    padding: 16px 40px;
    border-radius: 40px;
    text-align: center;
    width: fit-content;
    margin: 0 auto;
  }

  /* ── Swipe cue ── */
  .swipe-cue {
    position: absolute;
    bottom: 80px;
    right: 64px;
    font-size: 20px;
    color: ${NAVY};
    font-weight: 600;
    opacity: 0.6;
  }

  /* ── Bottom bar ── */
  .bottom-bar {
    position: absolute;
    bottom: 0; left: 0; right: 0;
    height: 52px;
    background: ${BLUE};
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .bottom-bar-text {
    color: ${WHITE};
    font-size: 20px;
    font-weight: 600;
    letter-spacing: 2px;
    text-transform: uppercase;
  }
</style>
</head>
<body>
<div class="slide">
  ${slideNumber ? `<div class="slide-number">${slideNumber}</div>` : ''}
  ${isHook ? `<div class="tag-pill">TECH &amp; AI UPDATE</div>` : ''}
  <div class="headline">${slide.headline}</div>
  <div class="subheadline">${slide.subheadline}</div>
  <div class="divider"></div>
  ${centerContent}
  ${isHook ? `<div class="swipe-cue">Swipe to explore →</div>` : ''}
  <div class="bottom-bar">
    <div class="bottom-bar-text">Tech &amp; AI Weekly</div>
  </div>
</div>
</body>
</html>`;
}

function getVisualEmoji(description) {
  if (!description) return '✦';
  const d = description.toLowerCase();
  if (d.includes('robot')) return '🤖';
  if (d.includes('graph') || d.includes('chart')) return '📊';
  if (d.includes('quantum') || d.includes('computer')) return '💻';
  if (d.includes('code') || d.includes('programming')) return '👨‍💻';
  if (d.includes('brain') || d.includes('neural')) return '🧠';
  if (d.includes('rocket') || d.includes('launch')) return '🚀';
  if (d.includes('cloud')) return '☁️';
  if (d.includes('phone') || d.includes('mobile')) return '📱';
  if (d.includes('camera') || d.includes('vision')) return '👁️';
  if (d.includes('money') || d.includes('fund')) return '💰';
  return '⚡';
}

// ─── MAIN ─────────────────────────────────────────────────────────────────
async function main() {
  mkdirSync('./output', { recursive: true });

  console.log(`Launching Puppeteer...`);
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  const results = [];

  for (let i = 0; i < content.slides.length; i++) {
    const slide = content.slides[i];
    console.log(`[${slide.id}] Rendering slide ${i + 1}/6...`);

    const page = await browser.newPage();
    await page.setViewport({ width: 1080, height: 1080, deviceScaleFactor: 1 });
    await page.setContent(getSlideHTML(slide, i), { waitUntil: 'networkidle0' });

    const localPath = `./output/${slide.id}.png`;
    await page.screenshot({ path: localPath, type: 'png' });
    await page.close();

    console.log(`[${slide.id}] Saved. Uploading to Cloudinary...`);

    const dateSlug = new Date().toISOString().slice(0, 10);
    const upload = await uploadMedia(localPath, {
      folder: `carousel/${FOLDER_SLUG}/${dateSlug}`,
      publicId: slide.id,
      tags: ['carousel', 'linkedin', FOLDER_SLUG],
    });

    results.push({ slide: slide.id, url: upload.url });
    console.log(`[${slide.id}] DONE — ${upload.url}`);
  }

  await browser.close();

  console.log('\n=== Slide Results ===');
  console.log(JSON.stringify(results, null, 2));
  console.log('\n✓ All slides rendered and uploaded!');
  console.log(`✓ Thumbnail URL: ${results[0].url}`);
}

main().catch(e => { console.error(e); process.exit(1); });
